### ISSUE TITLE
Steven Universe Unleash the Light

### ISSUE THREAD

**Issue by Jorshuask** [strato-emu/compat-list#1467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

-1970 

### Android Version

11

### SoC type

Exynos

### Device GSMArena link

https://m.gsmarena.com/samsung_galaxy_a50-9554.php

### Game Behaviour

The game crash in the beginning when you start

El juego se sale cuando le das a start 

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

I106EmuMainCreateDevice: Vulkan Device:
Name: Mali-G72
Type: IntegratedGpu
Driver ID: ArmProprietary
Vulkan Version: 1.1.131
Driver Version: 26.0.0
Queues:
* 2xGCT--: TSB64 MIG(1x1x1) <--
Extensions:
* VK_KHR_incremental_present (v0.0.1)
* VK_EXT_hdr_metadata (v0.0.2)
* VK_KHR_shared_presentable_image (v0.0.1)
* VK_GOOGLE_display_timing (v0.0.1)
* VK_KHR_16bit_storage (v0.0.1)
* VK_KHR_8bit_storage (v0.0.1)
* VK_KHR_bind_memory2 (v0.0.1)
* VK_KHR_buffer_device_address (v0.0.1)
* VK_KHR_create_renderpass2 (v0.0.1)
* VK_KHR_dedicated_allocation (v0.0.3)
* VK_KHR_depth_stencil_resolve (v0.0.1)
* VK_KHR_descriptor_update_template (v0.0.1)
* VK_KHR_device_group (v0.0.4)
* VK_KHR_driver_properties (v0.0.1)
* VK_KHR_external_fence (v0.0.1)
* VK_KHR_external_fence_fd (v0.0.1)
* VK_KHR_external_memory (v0.0.1)
* VK_KHR_external_memory_fd (v0.0.1)
* VK_KHR_external_semaphore (v0.0.1)
* VK_KHR_external_semaphore_fd (v0.0.1)
* VK_KHR_get_memory_requirements2 (v0.0.1)
* VK_KHR_image_format_list (v0.0.1)
* VK_KHR_imageless_framebuffer (v0.0.1)
* VK_KHR_maintenance1 (v0.0.2)
* VK_KHR_maintenance2 (v0.0.1)
* VK_KHR_maintenance3 (v0.0.1)
* VK_KHR_multiview (v0.0.1)
* VK_KHR_relaxed_block_layout (v0.0.1)
* VK_KHR_sampler_mirror_clamp_to_edge (v0.0.3)
* VK_KHR_sampler_ycbcr_conversion (v0.0.14)
* VK_KHR_separate_depth_stencil_layouts (v0.0.1)
* VK_KHR_shader_draw_parameters (v0.0.1)
* VK_KHR_shader_float16_int8 (v0.0.1)
* VK_KHR_shader_float_controls (v0.0.4)
* VK_KHR_shader_subgroup_extended_types (v0.0.1)
* VK_KHR_spirv_1_4 (v0.0.1)
* VK_KHR_storage_buffer_storage_class (v0.0.1)
* VK_KHR_timeline_semaphore (v0.0.2)
* VK_KHR_uniform_buffer_standard_layout (v0.0.1)
* VK_KHR_variable_pointers (v0.0.1)
* VK_KHR_vulkan_memory_model (v0.0.3)
* VK_EXT_global_priority (v0.0.2)
* VK_EXT_host_query_reset (v0.0.1)
* VK_EXT_index_type_uint8 (v0.0.1)
* VK_EXT_inline_uniform_block (v0.0.1)
* VK_EXT_line_rasterization (v0.0.1)
* VK_EXT_queue_family_foreign (v0.0.1)
* VK_EXT_scalar_block_layout (v0.0.1)
* VK_EXT_separate_stencil_usage (v0.0.1)
* VK_EXT_texture_compression_astc_hdr (v0.0.1)
* VK_EXT_shader_subgroup_ballot (v0.0.1)
* VK_EXT_shader_subgroup_vote (v0.0.1)
* VK_EXT_transform_feedback (v0.0.1)
* VK_EXT_external_memory_dma_buf (v0.0.1)
* VK_EXT_image_drm_format_modifier (v0.0.1)
* VK_ANDROID_external_memory_android_hardware_buffer (v0.0.3)
* VK_KHR_swapchain (v0.0.70)
Traits:
* Supports U8 Indices: true
* Supports Sampler Mirror Clamp To Edge: false
* Supports Sampler Reduction Mode: false
* Supports Custom Border Color (Without Format): false
* Supports Anisotropic Filtering: false
* Supports Last Provoking Vertex: false
* Supports Logical Operations: false
* Supports Vertex Attribute Divisor: false
* Supports Vertex Attribute Zero Divisor: false
* Supports Push Descriptors: false
* Supports Imageless Framebuffers: true
* Supports Global Priority: true
* Supports Multiple Viewports: false
* Supports Shader Viewport Index: false
* Supports SPIR-V 1.4: true
* Supports Shader Invocation Demotion: false
* Supports 16-bit FP: true
* Supports 8-bit Integers: true
* Supports 16-bit Integers: true
* Supports 64-bit Integers: false
* Supports Atomic 64-bit Integers: false
* Supports Floating Point Behavior Control: true
* Supports Image Read Without Format: true
* Supports List Primitive Topology Restart: false
* Supports Patch List Primitive Topology Restart: false
* Supports Transform Feedback: false
* Supports Geometry Shaders: true
*  Supports Vertex Pipeline Stores and Atomics: false
* Supports Fragment Stores and Atomics: true
* Supports Shader Storage Image Write Without Format: true
*Supports Subgroup Vote: true
* Subgroup Size: 4
* BCn Support: 0000000
Quirks:
* Needs Individual Texture Binding Writes: false
* VkImage Mutable Format is costly: false
* Adreno Relaxed Format Aliasing: false
* Adreno Broken Format Reporting: false
* Broken Descriptor Aliasing: false
* Relaxed Render Pass Compatibility: false
* Max Subpass Count: 4294967295
* Max Global Queue Priority: High
W473EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W474EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W475EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W477EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W477EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W479EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W480EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W481EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W482EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W483EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W488EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W490EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W491EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W492EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W493EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W494EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W495EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W497EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W499EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W500EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W501EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W502EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W502EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W503EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W505EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W506EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W506EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W507EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W508EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W508EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W509EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W510EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W511EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W512EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W513EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W514EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W515EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W515EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W517EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W518EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W519EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W520EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W521EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W522EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W522EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W524EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W525EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W525EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W526EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W527EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W528EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W529EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W530EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W531EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W532EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W532EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W533EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W534EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W535EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W536EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W538EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W539EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W540EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W541EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W542EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W543EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W544EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W546EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W547EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W548EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W549EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W550EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W551EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W552EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W553EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W554EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W554EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W555EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W556EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W557EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W558EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W559EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W560EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W561EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W562EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W563EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W564EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W565EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W566EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W567EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W567EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W568EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W569EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W570EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W571EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W572EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W573EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W574EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W574EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W575EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W576EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W577EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W579EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W580EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W581EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W582EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W583EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W584EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W585EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W586EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W586EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W587EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W588EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W589EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W590EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W591EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W592EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W593EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W594EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W595EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W595EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W597EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W598EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W599EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W600EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W601EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W602EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W603EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W604EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W606EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W607EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W608EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W609EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W610EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W610EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W611EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W612EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W615EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W616EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W618EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W619EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W620EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W625EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W628EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W630EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W631EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W632EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W634EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W641EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W643EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W645EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W647EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W648EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W650EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W651EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W652EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W654EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W656EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W658EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W659EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W661EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W667EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W669EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W671EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W682EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W685EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W692EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W698EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W701EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W703EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W711EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W712EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W712EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W716EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W717EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W718EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W718EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W719EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W721EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W722EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W723EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W724EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W725EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W726EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W727EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W729EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W730EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W731EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W732EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W733EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W734EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W735EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W736EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W737EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W738EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W739EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W740EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W741EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W741EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W743EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W744EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W744EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W745EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W747EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W748EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W749EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W750EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W751EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W752EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W753EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W754EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W755EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W757EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W758EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W759EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W759EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W760EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W761EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W764EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W765EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W766EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W768EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W769EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W771EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W773EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W774EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W775EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W777EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W778EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W779EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W780EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W781EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W782EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W783EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W784EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W785EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W786EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W787EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W788EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W789EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W790EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W792EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W793EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W794EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W794EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W795EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W796EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W798EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W801EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W802EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W803EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W804EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W805EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W806EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W808EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W809EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W811EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W813EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W814EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W815EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W816EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W817EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W818EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W819EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W820EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W821EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W823EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W824EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W825EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W828EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W829EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W830EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W833EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W834EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W835EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W836EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W837EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W838EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W840EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W844EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W846EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W847EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W850EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W851EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W852EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W854EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W855EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W856EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W856EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W857EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W858EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W859EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W860EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W862EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W863EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W864EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W865EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W866EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W866EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W868EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W869EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W870EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W871EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W873EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W874EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W875EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W876EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W877EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W878EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W879EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W880EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W881EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W882EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W883EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W884EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W885EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W886EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W887EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W888EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W889EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W890EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W891EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W893EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W894EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W895EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W896EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W898EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W899EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W900EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W901EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W902EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W903EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W904EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W906EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W907EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W909EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W909EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W911EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W912EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W913EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W914EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W915EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W915EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W916EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W917EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W918EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W919EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W920EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W921EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W922EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W923EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W924EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W925EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W926EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W928EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W929EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W929EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
W930EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support
I931EmuMainPipelineManager: Loaded 358 graphics pipelines in 461ms
I934EmuMainSerialisePipelineCache: Wrote Vulkan pipeline cache to /storage/emulated/0/Android/data/skyline.emu/files/vk_graphics_pipeline_cache/0100A5C00D162000/B51300001000216200008006B6A803E0637DA094ECDED4CEBEE2049B (size: 0x3E8B2 bytes)
I936EmuMainNPDM Metadata:
Title: ID: 100A5C00D162000, Version: 0
Main Thread: Priority: 44, Stack Size: 0x100000
Scheduler: Ideal Core: 0, Core Mask: 0111, Priority: 28 - 59
Kernel Version: v9.1
I952EmuMainLoadExeFs: Loaded 'rtld.nso' at 0x800000000 (.text @ 0x800001000)
I1878EmuMainLoadExeFs: Loaded 'main.nso' at 0x800005000 (.text @ 0x800006000)
I1992EmuMainLoadExeFs: Loaded 'subsdk0.nso' at 0x803647000 (.text @ 0x803648000)
I2141EmuMainLoadExeFs: Loaded 'sdk.nso' at 0x803D40000 (.text @ 0x803D42000)
I2141EmuMainStarting "Cuphead" (0100A5C00D162000) v1.2.0 by "Studio MDHR"
I2142EmuMainExecute: Starting main HOS thread

**Comment by AccordiaDusk** [comment]
The game actually starts and goes In-game with a snapdragon 845 and 4GB RAM. But has several graphical glitches all over, tested with latest Vulkan and Mesa Turnip drivers and the result is just the same.

**Comment by marcos7117** [comment]
Still with bugs in Skyline edge latest version
