### ISSUE TITLE
Super Mario Bros. Wonder

### ISSUE THREAD

**Issue by Ishan0981** [strato-emu/compat-list#1636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Strato Build 36

### Android Version

13

### SoC type

Exynos

### Device GSMArena link

https://m.gsmarena.com/samsung_galaxy_note10_lite-10003.php

### Game Behaviour

Game Is Not Showing
Keys Version: 16.1.0
Screenshot:
![Screenshot_20231018-012420](https://github.com/strato-emu/compat-list/assets/145665569/3e9c42ee-b778-45b8-bc0c-154104acf3b2)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

Don't Have Because Game Is Not Showing

**Comment by Crytonics** [comment]
You need redump newer version of keys, i will close this because this is not strato problem.
