### ISSUE TITLE
Loop8: Summer of Gods

### ISSUE THREAD

**Issue by ikhoeyZX** [strato-emu/compat-list#1645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

strato-git

### Android Version

13

### SoC type

Exynos

### Device GSMArena link

https://m.gsmarena.com/samsung_galaxy_m33-11404.php

### Game Behaviour

-. texture glitch 
-. memory leak (random crash due freeup memory got denied)
![Screenshot_20231217_014440](https://github.com/strato-emu/compat-list/assets/79812109/032bd12a-08ac-4f69-8997-d9b0df5deb7b)
![Screenshot_20231217_014516](https://github.com/strato-emu/compat-list/assets/79812109/ad92c31d-ed01-4a7a-9c83-d0f4d4fb03f5)
![Screenshot_20231217_015247](https://github.com/strato-emu/compat-list/assets/79812109/70963561-8352-499b-bbed-aa6e493e4b82)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.log.zip](https://github.com/strato-emu/compat-list/files/13693381/emulation.log.zip)

**Comment by ikhoeyZX** [comment]
oh man
browser issue
title got reset

**Comment by Crytonics** [comment]
We don't support custom builds.
