### ISSUE TITLE
Ben 10 Power Trip

### ISSUE THREAD

**Issue by Ishan0981** [strato-emu/compat-list#1646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Strato Current GitHub Build

### Android Version

13

### SoC type

Mediatek

### Device GSMArena link

https://m.gsmarena.com/oppo_reno10-ampp-12414.php

### Game Behaviour

This game have many Graphical issues

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.log.txt](https://github.com/strato-emu/compat-list/files/13797611/emulation.log.4.txt)

**Comment by Crytonics** [comment]
We don't support custom builds. And strato isn't released yet.
