### ISSUE TITLE
Minecraft

### ISSUE THREAD

**Issue by David90H** [strato-emu/compat-list#1655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Nose

### Android Version

10

### SoC type

Mediatek

### Device GSMArena link

https://www.gsmarena.com/infinix_gt_20_pro_specs_and_officiallooking_images_leak-news-62613.php

### Game Behaviour

Nose

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

Minecraft

**Comment by David90H** [comment]
Me gusto

**Comment by David90H** [comment]
Ya voy a explotar🎉

**Comment by Crytonics** [comment]
Duplicate of #1604
